### ISSUE TITLE
How to use the notebook with a pd dataframe with only one column?

### ISSUE THREAD

**Issue by ShivanshuPurohit** [dylanjcastillo/nlp-snippets#2]
I have a list of words for professional skills. Rather than multiple columns for news I only have a single column. Any help will be appreciated.

**Comment by dylanjcastillo** [comment]
Hi @ShivanshuPurohit, you can use `pandas` to read a `DataFrame` of 1 column. Then, you can apply the same things shown in the notebook but ignoring the part where you concatenate all the columns.
