### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by khannadheeraj** [dylanjcastillo/nlp-snippets#6]
While running the `mbkmeans_clusters(X=vectorized_docs, k=50, print_silhouette_values=True)` It is giving the AttributeError

**Comment by khannadheeraj** [comment]
it is the issue of numpy version. for numpy==1.21.0  code is working fine

**Comment by dylanjcastillo** [comment]
Thank you!
